version: "3.8"
services:
 playbook: #docker run -it -v ${PWD}:/work -w /work -p 5000:5000
  container_name: playbook
  image: alpine:latest
  build:
    context: ./playbook
    target: debug
  volumes:
  - ./playbook/src:/work/
  ports:
    - 5000:5000